name: Deploy to Hostinger (metodologoinfinity)

on:
  push:
    branches: [ "main" ]   # troque se usar outra branch

env:
  # Enviado para o Vite (process.env.BASE_PATH)
  BASE_PATH: /metodologoinfinity/
  # Pasta de destino na Hostinger
  SERVER_DIR: /public_html/metodologoinfinity/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: npm install

      # NÃO passamos --base aqui; o base vem do process.env.BASE_PATH
      - name: Build (usa BASE_PATH do env)
        run: npm run build

      # Seu projeto gera dist/public/index.html; caímos nele primeiro
      - name: Choose publish dir
        id: choose
        shell: bash
        run: |
          if [ -f "dist/public/index.html" ]; then
            echo "PUBDIR=dist/public" >> $GITHUB_OUTPUT
          elif [ -f "dist/index.html" ]; then
            echo "PUBDIR=dist" >> $GITHUB_OUTPUT
          else
            echo "Nenhum index.html encontrado em dist/"; ls -la dist || true; exit 1
          fi
          echo "Publicando a partir de: ${{ steps.choose.outputs.PUBDIR }}"

      - name: List build output
        run: ls -la "${{ steps.choose.outputs.PUBDIR }}"

      # .htaccess pra SPA e pra não reescrever /assets
      - name: Create .htaccess (SPA)
        run: |
          cat > "${{ steps.choose.outputs.PUBDIR }}/.htaccess" << 'EOF'
          Options -Indexes
          DirectoryIndex index.html
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /metodologoinfinity/
            # não reescrever arquivos/pastas reais
            RewriteCond %{REQUEST_FILENAME} -f [OR]
            RewriteCond %{REQUEST_FILENAME} -d
            RewriteRule ^ - [L]
            # fallback SPA
            RewriteRule . /metodologoinfinity/index.html [L]
          </IfModule>
          EOF
- name: Force asset paths to subfolder (failsafe)
  run: |
    FILE="${{ steps.choose.outputs.PUBDIR }}/index.html"
    sed -i 's|src="/assets/|src="/metodologoinfinity/assets/|g' "$FILE"
    sed -i 's|href="/assets/|href="/metodologoinfinity/assets/|g' "$FILE"

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}     # host (ou IP) sem ftp:// e sem :21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}         # 21
          local-dir: ${{ steps.choose.outputs.PUBDIR }}/
          server-dir: ${{ env.SERVER_DIR }}
          dangerous-clean-slate: true
          log-level: verbose
