name: Deploy to Hostinger (metodologoinfinity)

on:
  push:
    branches: [ "main" ]  # troque se usar outra branch

env:
  BASE_PATH: /metodologoinfinity/
  SERVER_DIR: /public_html/metodologoinfinity/

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install deps
        run: npm install

      # Build sem --base; o Vite lê BASE_PATH do env (vite.config.ts)
      - name: Build (usa BASE_PATH do env)
        run: npm run build

      # Descobre onde saiu o index.html
      - name: Choose publish dir
        id: choose
        shell: bash
        run: |
          if [ -f "dist/public/index.html" ]; then
            echo "PUBDIR=dist/public" >> $GITHUB_OUTPUT
          elif [ -f "dist/index.html" ]; then
            echo "PUBDIR=dist" >> $GITHUB_OUTPUT
          else
            echo "Nenhum index.html encontrado em dist/"; ls -la dist || true; exit 1
          fi
          echo "Publicando a partir de: ${{ steps.choose.outputs.PUBDIR }}"

      - name: List build output
        run: ls -la "${{ steps.choose.outputs.PUBDIR }}"

      # Failsafe: se por algum motivo o Vite gerar /assets/... sem a subpasta,
      # substitui no HTML final para /metodologoinfinity/assets/...
      - name: Force asset paths to subfolder (failsafe)
        shell: bash
        run: |
          FILE="${{ steps.choose.outputs.PUBDIR }}/index.html"
          if grep -q 'src="/assets/' "$FILE" || grep -q 'href="/assets/' "$FILE"; then
            sed -i 's|src="/assets/|src="/metodologoinfinity/assets/|g' "$FILE"
            sed -i 's|href="/assets/|href="/metodologoinfinity/assets/|g' "$FILE"
            echo "Corrigidos paths de assets no index.html"
          else
            echo "Paths de assets já corretos"
          fi

      # Cria .htaccess sem heredoc (usando printf para evitar erro de YAML)
      - name: Create .htaccess (SPA)
        shell: bash
        run: |
          HT="${{ steps.choose.outputs.PUBDIR }}/.htaccess"
          printf '%s\n' \
            'Options -Indexes' \
            'DirectoryIndex index.html' \
            '<IfModule mod_rewrite.c>' \
            '  RewriteEngine On' \
            '  RewriteBase /metodologoinfinity/' \
            '  RewriteCond %{REQUEST_FILENAME} -f [OR]' \
            '  RewriteCond %{REQUEST_FILENAME} -d' \
            '  RewriteRule ^ - [L]' \
            '  RewriteRule . /metodologoinfinity/index.html [L]' \
            '</IfModule>' > "$HT"
          echo "Gerado $HT"

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}     # host ou IP (sem ftp:// e sem :21)
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}         # 21
          local-dir: ${{ steps.choose.outputs.PUBDIR }}/
          server-dir: ${{ env.SERVER_DIR }}
          dangerous-clean-slate: true
          log-level: verbose
